

import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import 'cityQuery.dart';
import 'getAutocomplete.dart';

part 'autocompleteApi.g.dart';
@RestApi()
abstract class AutocompleteApi {
  factory AutocompleteApi(Dio dioData) = _AutocompleteApi;

  @POST('/address')
  @FormUrlEncoded()
  Future<Autogenerated> getAutofill(
  @Body() String json,
      );

}