import 'package:json_annotation/json_annotation.dart';
import 'package:weather_simple/dadata/suggestions.dart';
part 'getAutocomplete.g.dart';

@JsonSerializable()
class Autogenerated {
  List<Suggestions>? suggestions;

  Autogenerated({this.suggestions});


  factory Autogenerated.fromJson(Map<String, dynamic> json) => _$AutogeneratedFromJson(json);

}




