// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'getAutocomplete.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Autogenerated _$AutogeneratedFromJson(Map<String, dynamic> json) =>
    Autogenerated(
      suggestions: (json['suggestions'] as List<dynamic>?)
          ?.map((e) => Suggestions.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$AutogeneratedToJson(Autogenerated instance) =>
    <String, dynamic>{
      'suggestions': instance.suggestions,
    };
