import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:injectable/injectable.dart';

import '../coord.dart';
import '../dadata/autocompleteApi.dart';
import '../dadata/cityQuery.dart';
import '../dadata/fromBound.dart';
import '../dadata/getAutocomplete.dart';
import '../dadata/locations.dart';
import '../getWeatherResponse.dart';
import '../wether_api.dart';
@singleton
class DadataRepository {
  final AutocompleteApi _dadataApi;
  DadataRepository(this._dadataApi);


  Future<Autogenerated?> getAutocomplete() async {
    try {
      var response = await _dadataApi.getAutofill(jsonEncode(CityQuery(query: 'москва',fromBound: FromBound(value: 'city'), toBound: FromBound(value: 'city'), locations: [Locations(countryIsoCode: '*')])));

      // var response = await _weatherApi.getWeather(coordinate.latitude.toString(), coordinate.longitude.toString(), '1ca4000c3a81765bcd106423bf367de7','ru');
      print(response);
      try {

      } catch (e){
        print(e);
      }
      return response;
    } catch (e) {
      return null;
    }
  }
}